title: Ahmed Al Balushi # your name (or website title) here
logo: "/images/logo2.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  
  Working on solving problems with the aid of technology. 
  Exponential thinker, Goal oriented. 
  Interested in using Exponential Technologies for building an Abundant World. 
  <br>
  Currently Working on building Mobile apps for special clients. Graduated from
  California State University Northridge with a degree in Computer Science. My plan in 5 years
  is to implement a smart irrigation systems for College Campuses and Golf courses.
 
  <a href="https://www.linkedin.com/in/ahmed-al-balushi-31775b146/">View My LinkedIn Profile</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
